import { Users, Briefcase, CreditCard } from "lucide-react";
import { GenericEntityPage, type ColumnDef, type FormFieldDef } from "@/components/generic-entity-page";
const BASE = "/api/industries/consulting";
const S = [{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }];
const cc: ColumnDef[] = [{key:"lastName",header:"Name",render:(_,r)=>`${r.lastName}, ${r.firstName}`},{key:"company",header:"Company"},{key:"email",header:"Email"},{key:"status",header:"Status"}];
const cf: FormFieldDef[] = [{key:"firstName",label:"First Name",required:true},{key:"lastName",label:"Last Name",required:true},{key:"company",label:"Company"},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone",type:"tel"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"active"}];
const coc: ColumnDef[] = [{key:"lastName",header:"Name",render:(_,r)=>`${r.lastName}, ${r.firstName}`},{key:"email",header:"Email"},{key:"specialization",header:"Specialization"},{key:"billRate",header:"Rate",render:v=>v?`$${Number(v).toFixed(2)}/hr`:"—"},{key:"status",header:"Status"}];
const cof: FormFieldDef[] = [{key:"firstName",label:"First Name",required:true},{key:"lastName",label:"Last Name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone",type:"tel"},{key:"specialization",label:"Specialization"},{key:"billRate",label:"Bill Rate",type:"number"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"active"}];
const ec: ColumnDef[] = [{key:"title",header:"Engagement"},{key:"clientId",header:"Client ID"},{key:"budget",header:"Budget",render:v=>v?`$${Number(v).toLocaleString()}`:"—"},{key:"status",header:"Status"}];
const ef: FormFieldDef[] = [{key:"clientId",label:"Client ID",type:"number",required:true},{key:"consultantId",label:"Consultant ID",type:"number"},{key:"title",label:"Title",required:true},{key:"scope",label:"Scope"},{key:"startDate",label:"Start Date",type:"date"},{key:"endDate",label:"End Date",type:"date"},{key:"budget",label:"Budget",type:"number"},{key:"status",label:"Status",type:"select",options:[...S,{value:"completed",label:"Completed"}],defaultValue:"active"}];
export function ConsultingClients() { return <GenericEntityPage title="Clients" icon={<Users className="h-8 w-8 text-blue-600"/>} description="Manage consulting clients" entityLabel="Client" apiPath={`${BASE}/clients`} columns={cc} formFields={cf} searchFields={["firstName","lastName","company"]}/>; }
export function ConsultingConsultants() { return <GenericEntityPage title="Consultants" icon={<Briefcase className="h-8 w-8 text-blue-600"/>} description="Manage consultants" entityLabel="Consultant" apiPath={`${BASE}/consultants`} columns={coc} formFields={cof} searchFields={["firstName","lastName","specialization"]}/>; }
export function ConsultingEngagements() { return <GenericEntityPage title="Engagements" icon={<CreditCard className="h-8 w-8 text-blue-600"/>} description="Manage client engagements" entityLabel="Engagement" apiPath={`${BASE}/engagements`} columns={ec} formFields={ef} searchFields={["title","status"]}/>; }
