import { Users, FileWarning, Package } from "lucide-react";
import { GenericEntityPage, type ColumnDef, type FormFieldDef } from "@/components/generic-entity-page";
const BASE = "/api/industries/government";
const S = [{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }];
const cc: ColumnDef[] = [{key:"lastName",header:"Name",render:(_,r)=>`${r.lastName}, ${r.firstName}`},{key:"email",header:"Email"},{key:"dateOfBirth",header:"DOB"},{key:"status",header:"Status"}];
const cf: FormFieldDef[] = [{key:"firstName",label:"First Name",required:true},{key:"lastName",label:"Last Name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone",type:"tel"},{key:"dateOfBirth",label:"Date of Birth",type:"date"},{key:"address",label:"Address"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"active"}];
const pc: ColumnDef[] = [{key:"type",header:"Type"},{key:"applicantName",header:"Applicant"},{key:"issueDate",header:"Issued"},{key:"expiryDate",header:"Expires"},{key:"status",header:"Status"}];
const pf: FormFieldDef[] = [{key:"type",label:"Type",required:true},{key:"applicantName",label:"Applicant Name",required:true},{key:"description",label:"Description"},{key:"fee",label:"Fee",type:"number"},{key:"issueDate",label:"Issue Date",type:"date"},{key:"expiryDate",label:"Expiry Date",type:"date"},{key:"status",label:"Status",type:"select",options:[{value:"pending",label:"Pending"},{value:"approved",label:"Approved"},{value:"rejected",label:"Rejected"}],defaultValue:"pending"}];
const src: ColumnDef[] = [{key:"type",header:"Type"},{key:"description",header:"Description",render:v=>v?.length>50?`${v.slice(0,50)}...`:v},{key:"priority",header:"Priority"},{key:"status",header:"Status"}];
const srf: FormFieldDef[] = [{key:"citizenId",label:"Citizen ID",type:"number",required:true},{key:"type",label:"Type",required:true},{key:"description",label:"Description",required:true},{key:"priority",label:"Priority",type:"select",options:[{value:"low",label:"Low"},{value:"normal",label:"Normal"},{value:"high",label:"High"},{value:"urgent",label:"Urgent"}],defaultValue:"normal"},{key:"status",label:"Status",type:"select",options:[{value:"open",label:"Open"},{value:"in_progress",label:"In Progress"},{value:"closed",label:"Closed"}],defaultValue:"open"}];
export function GovernmentCitizens() { return <GenericEntityPage title="Citizens" icon={<Users className="h-8 w-8 text-indigo-600"/>} description="Manage citizen records" entityLabel="Citizen" apiPath={`${BASE}/citizens`} columns={cc} formFields={cf} searchFields={["firstName","lastName","email"]}/>; }
export function GovernmentPermits() { return <GenericEntityPage title="Permits" icon={<FileWarning className="h-8 w-8 text-indigo-600"/>} description="Manage permits and licenses" entityLabel="Permit" apiPath={`${BASE}/permits`} columns={pc} formFields={pf} searchFields={["type","applicantName","status"]}/>; }
export function GovernmentServiceRequests() { return <GenericEntityPage title="Service Requests" icon={<Package className="h-8 w-8 text-indigo-600"/>} description="Track citizen service requests" entityLabel="Request" apiPath={`${BASE}/service-requests`} columns={src} formFields={srf} searchFields={["type","description","priority"]}/>; }
