import { Hotel, Users, CreditCard } from "lucide-react";
import { GenericEntityPage, type ColumnDef, type FormFieldDef } from "@/components/generic-entity-page";
const BASE = "/api/industries/hospitality";
const S = [{ value: "available", label: "Available" }, { value: "occupied", label: "Occupied" }, { value: "maintenance", label: "Maintenance" }];
const rc: ColumnDef[] = [{key:"roomNumber",header:"Room"},{key:"type",header:"Type"},{key:"pricePerNight",header:"$/night",render:v=>`$${Number(v).toFixed(2)}`},{key:"capacity",header:"Capacity"},{key:"status",header:"Status"}];
const rf: FormFieldDef[] = [{key:"roomNumber",label:"Room Number",required:true},{key:"type",label:"Type",required:true},{key:"pricePerNight",label:"Price/Night",type:"number",required:true},{key:"capacity",label:"Capacity",type:"number"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"available"}];
const gc: ColumnDef[] = [{key:"lastName",header:"Name",render:(_,r)=>`${r.lastName}, ${r.firstName}`},{key:"email",header:"Email"},{key:"nationality",header:"Nationality"},{key:"status",header:"Status"}];
const gf: FormFieldDef[] = [{key:"firstName",label:"First Name",required:true},{key:"lastName",label:"Last Name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone",type:"tel"},{key:"nationality",label:"Nationality"},{key:"status",label:"Status",type:"select",options:[{value:"active",label:"Active"},{value:"inactive",label:"Inactive"}],defaultValue:"active"}];
const bc: ColumnDef[] = [{key:"checkIn",header:"Check In"},{key:"checkOut",header:"Check Out"},{key:"roomId",header:"Room ID"},{key:"guestId",header:"Guest ID"},{key:"totalAmount",header:"Total",render:v=>v?`$${Number(v).toFixed(2)}`:"—"},{key:"status",header:"Status"}];
const bf: FormFieldDef[] = [{key:"roomId",label:"Room ID",type:"number",required:true},{key:"guestId",label:"Guest ID",type:"number",required:true},{key:"checkIn",label:"Check In",type:"date",required:true},{key:"checkOut",label:"Check Out",type:"date",required:true},{key:"totalAmount",label:"Total Amount",type:"number"},{key:"status",label:"Status",type:"select",options:[{value:"confirmed",label:"Confirmed"},{value:"checked_in",label:"Checked In"},{value:"checked_out",label:"Checked Out"},{value:"cancelled",label:"Cancelled"}],defaultValue:"confirmed"}];
export function HospitalityRooms() { return <GenericEntityPage title="Rooms" icon={<Hotel className="h-8 w-8 text-orange-500"/>} description="Manage rooms" entityLabel="Room" apiPath={`${BASE}/rooms`} columns={rc} formFields={rf} searchFields={["roomNumber","type"]}/>; }
export function HospitalityGuests() { return <GenericEntityPage title="Guests" icon={<Users className="h-8 w-8 text-orange-500"/>} description="Manage guest profiles" entityLabel="Guest" apiPath={`${BASE}/guests`} columns={gc} formFields={gf} searchFields={["firstName","lastName","nationality"]}/>; }
export function HospitalityBookings() { return <GenericEntityPage title="Bookings" icon={<CreditCard className="h-8 w-8 text-orange-500"/>} description="Manage bookings" entityLabel="Booking" apiPath={`${BASE}/bookings`} columns={bc} formFields={bf} searchFields={["status"]}/>; }
