import { Newspaper, Package, CreditCard } from "lucide-react";
import { GenericEntityPage, type ColumnDef, type FormFieldDef } from "@/components/generic-entity-page";
const BASE = "/api/industries/media";
const ac: ColumnDef[] = [{key:"title",header:"Article"},{key:"author",header:"Author"},{key:"category",header:"Category"},{key:"status",header:"Status"},{key:"publishedAt",header:"Published"}];
const af: FormFieldDef[] = [{key:"title",label:"Title",required:true},{key:"content",label:"Content"},{key:"author",label:"Author"},{key:"category",label:"Category"},{key:"status",label:"Status",type:"select",options:[{value:"draft",label:"Draft"},{value:"review",label:"Review"},{value:"published",label:"Published"},{value:"archived",label:"Archived"}],defaultValue:"draft"}];
const asc: ColumnDef[] = [{key:"name",header:"Asset"},{key:"type",header:"Type"},{key:"fileSize",header:"Size",render:v=>v?`${(v/1024).toFixed(0)}KB`:"—"},{key:"status",header:"Status"}];
const asf: FormFieldDef[] = [{key:"name",label:"Name",required:true},{key:"type",label:"Type",required:true},{key:"url",label:"URL"},{key:"alt",label:"Alt Text"},{key:"status",label:"Status",type:"select",options:[{value:"active",label:"Active"},{value:"inactive",label:"Inactive"}],defaultValue:"active"}];
const cc: ColumnDef[] = [{key:"name",header:"Campaign"},{key:"type",header:"Type"},{key:"budget",header:"Budget",render:v=>v?`$${Number(v).toLocaleString()}`:"—"},{key:"status",header:"Status"}];
const cf: FormFieldDef[] = [{key:"name",label:"Name",required:true},{key:"type",label:"Type",required:true},{key:"budget",label:"Budget",type:"number"},{key:"startDate",label:"Start Date",type:"date"},{key:"endDate",label:"End Date",type:"date"},{key:"status",label:"Status",type:"select",options:[{value:"active",label:"Active"},{value:"paused",label:"Paused"},{value:"completed",label:"Completed"}],defaultValue:"active"}];
export function MediaArticles() { return <GenericEntityPage title="Articles" icon={<Newspaper className="h-8 w-8 text-red-600"/>} description="Manage content articles" entityLabel="Article" apiPath={`${BASE}/articles`} columns={ac} formFields={af} searchFields={["title","author","category"]}/>; }
export function MediaAssets() { return <GenericEntityPage title="Assets" icon={<Package className="h-8 w-8 text-red-600"/>} description="Manage media assets" entityLabel="Asset" apiPath={`${BASE}/assets`} columns={asc} formFields={asf} searchFields={["name","type"]}/>; }
export function MediaCampaigns() { return <GenericEntityPage title="Campaigns" icon={<CreditCard className="h-8 w-8 text-red-600"/>} description="Manage media campaigns" entityLabel="Campaign" apiPath={`${BASE}/campaigns`} columns={cc} formFields={cf} searchFields={["name","type"]}/>; }
