import { Building, Users, CreditCard } from "lucide-react";
import { GenericEntityPage, type ColumnDef, type FormFieldDef } from "@/components/generic-entity-page";
const BASE = "/api/industries/real-estate";
const S = [{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }];
const pc: ColumnDef[] = [{key:"name",header:"Property"},{key:"address",header:"Address"},{key:"type",header:"Type"},{key:"price",header:"Price",render:v=>v?`$${Number(v).toLocaleString()}`:"—"},{key:"status",header:"Status"}];
const pf: FormFieldDef[] = [{key:"name",label:"Name",required:true},{key:"address",label:"Address"},{key:"type",label:"Type",type:"select",required:true,options:[{value:"residential",label:"Residential"},{value:"commercial",label:"Commercial"},{value:"industrial",label:"Industrial"},{value:"land",label:"Land"}],defaultValue:"residential"},{key:"price",label:"Price",type:"number"},{key:"status",label:"Status",type:"select",options:[...S,{value:"available",label:"Available"},{value:"sold",label:"Sold"},{value:"rented",label:"Rented"}],defaultValue:"available"}];
const cc: ColumnDef[] = [{key:"lastName",header:"Name",render:(_,r)=>`${r.lastName}, ${r.firstName}`},{key:"email",header:"Email"},{key:"type",header:"Type"},{key:"status",header:"Status"}];
const cf: FormFieldDef[] = [{key:"firstName",label:"First Name",required:true},{key:"lastName",label:"Last Name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone",type:"tel"},{key:"type",label:"Type",type:"select",required:true,options:[{value:"buyer",label:"Buyer"},{value:"seller",label:"Seller"},{value:"tenant",label:"Tenant"}],defaultValue:"buyer"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"active"}];
const lc: ColumnDef[] = [{key:"propertyId",header:"Property ID"},{key:"clientId",header:"Client ID"},{key:"startDate",header:"Start"},{key:"endDate",header:"End"},{key:"rent",header:"Rent",render:v=>v?`$${Number(v).toLocaleString()}`:"—"},{key:"status",header:"Status"}];
const lf: FormFieldDef[] = [{key:"propertyId",label:"Property ID",type:"number",required:true},{key:"clientId",label:"Client ID",type:"number",required:true},{key:"startDate",label:"Start Date",type:"date",required:true},{key:"endDate",label:"End Date",type:"date"},{key:"rent",label:"Rent",type:"number"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"active"}];
export function RealEstateProperties() { return <GenericEntityPage title="Properties" icon={<Building className="h-8 w-8 text-teal-500"/>} description="Manage properties" entityLabel="Property" apiPath={`${BASE}/properties`} columns={pc} formFields={pf} searchFields={["name","address","type"]}/>; }
export function RealEstateClients() { return <GenericEntityPage title="Clients" icon={<Users className="h-8 w-8 text-teal-500"/>} description="Manage real estate clients" entityLabel="Client" apiPath={`${BASE}/clients`} columns={cc} formFields={cf} searchFields={["firstName","lastName","email"]}/>; }
export function RealEstateLeases() { return <GenericEntityPage title="Leases" icon={<CreditCard className="h-8 w-8 text-teal-500"/>} description="Manage lease agreements" entityLabel="Lease" apiPath={`${BASE}/leases`} columns={lc} formFields={lf} searchFields={["status"]}/>; }
