import { Truck, Users, Package } from "lucide-react";
import { GenericEntityPage, type ColumnDef, type FormFieldDef } from "@/components/generic-entity-page";
const BASE = "/api/industries/transportation";
const S = [{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }];
const vc: ColumnDef[] = [{key:"plateNumber",header:"Plate"},{key:"model",header:"Model"},{key:"capacity",header:"Capacity"},{key:"status",header:"Status"}];
const vf: FormFieldDef[] = [{key:"plateNumber",label:"Plate Number",required:true},{key:"model",label:"Model"},{key:"capacity",label:"Capacity",type:"number"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"active"}];
const dc: ColumnDef[] = [{key:"lastName",header:"Name",render:(_,r)=>`${r.lastName}, ${r.firstName}`},{key:"email",header:"Email"},{key:"licenseNumber",header:"License"},{key:"status",header:"Status"}];
const df: FormFieldDef[] = [{key:"firstName",label:"First Name",required:true},{key:"lastName",label:"Last Name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone",type:"tel"},{key:"licenseNumber",label:"License Number"},{key:"status",label:"Status",type:"select",options:S,defaultValue:"active"}];
const sc: ColumnDef[] = [{key:"origin",header:"Origin"},{key:"destination",header:"Destination"},{key:"pickupDate",header:"Pickup"},{key:"deliveryDate",header:"Delivery"},{key:"status",header:"Status"}];
const sf: FormFieldDef[] = [{key:"vehicleId",label:"Vehicle ID",type:"number"},{key:"driverId",label:"Driver ID",type:"number"},{key:"origin",label:"Origin",required:true},{key:"destination",label:"Destination",required:true},{key:"pickupDate",label:"Pickup Date",type:"date"},{key:"deliveryDate",label:"Delivery Date",type:"date"},{key:"status",label:"Status",type:"select",options:[{value:"pending",label:"Pending"},{value:"in_transit",label:"In Transit"},{value:"delivered",label:"Delivered"},{value:"cancelled",label:"Cancelled"}],defaultValue:"pending"}];
export function TransportationVehicles() { return <GenericEntityPage title="Vehicles" icon={<Truck className="h-8 w-8 text-slate-500"/>} description="Manage fleet vehicles" entityLabel="Vehicle" apiPath={`${BASE}/vehicles`} columns={vc} formFields={vf} searchFields={["plateNumber","model"]}/>; }
export function TransportationDrivers() { return <GenericEntityPage title="Drivers" icon={<Users className="h-8 w-8 text-slate-500"/>} description="Manage drivers" entityLabel="Driver" apiPath={`${BASE}/drivers`} columns={dc} formFields={df} searchFields={["firstName","lastName","licenseNumber"]}/>; }
export function TransportationShipments() { return <GenericEntityPage title="Shipments" icon={<Package className="h-8 w-8 text-slate-500"/>} description="Track shipments" entityLabel="Shipment" apiPath={`${BASE}/shipments`} columns={sc} formFields={sf} searchFields={["origin","destination","status"]}/>; }
